[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"

[context.production.environment]
  OPENAI_API_KEY = "sk-None-P2vWx1vrXDcq8aDb4IV5T3BlbkFJP1U5UurqedRdUJmzfKoa"
